### ISSUE TITLE
Show IP on mouseover or on click

### ISSUE THREAD

**Issue by sojusnik** [rostegg/public-ip-gnome-extension#12]
I configured this extension to show only the flag in the panel, but sometimes I also want to see the actual IP, therefore it would be very handy to see the IP on mouseover or when right-clicking on the flag, since left-clicking refreshes the icon manually AFACIR.

**Comment by rostegg** [comment]
So, looking through the [docs](https://developer.gnome.org/gtk3/stable/GtkButton.html), I did not notice a good way to intercept right click.

But it’s quite easy to intercept a mouseover, but I will make this function disabled by default, you can enable it in the settings.   

If there are no other suggestions, then at the weekend I will definitely add a feature.

**Comment by rostegg** [comment]
Now in settings can find switch:

![image](https://user-images.githubusercontent.com/11292722/69417818-1e805f00-0d22-11ea-919f-cf2ee42f5654.png)
Working example:

![image](https://raw.githubusercontent.com/rostegg/public-ip-gnome-extension/assets/example-on-mouseover.gif)

Now you can [manually install](https://github.com/rostegg/public-ip-gnome-extension/tree/master#how-to-install) and check update.  

If there are no suggestions and all work ok, i will add update on site and close issue, when the extension will be reviewed.

**Comment by sojusnik** [comment]
Works fine, thanks!
