### ISSUE TITLE
[Feature Request]: Change Position on the Panel

### ISSUE THREAD

**Issue by kebeda** [rostegg/public-ip-gnome-extension#14]
Can you add an option in the settings "Position on the Panel" with a dropdown [ left / center / right ]?
I prefer to see the IP address on the left side of the screen...

**Comment by rostegg** [comment]
Done, now it's look like this:

![image](https://user-images.githubusercontent.com/11292722/70421523-95cc2780-1a72-11ea-9ad1-f105e67b7b4a.png)

Now you can [manually install](https://github.com/rostegg/public-ip-gnome-extension/tree/master#how-to-install) and check update.

For now, updates will not be added to the site.

If everything is ok, then you can just close issue.

**Comment by rostegg** [comment]
Closed due to inactivity.
