### ISSUE TITLE
Error on 3.36 hotfix branch - Tried to construct an object without a GType;

### ISSUE THREAD

**Issue by mzylowski** [rostegg/public-ip-gnome-extension#17]
Hello,
I installed public-ip-gnome-extension on my gnome ubuntu 20.04
```
gnome-shell --version
GNOME Shell 3.36.0
```
Command used for install:
```
git clone -b gnome-3.36-hotfix https://github.com/rostegg/public-ip-gnome-extension.git ~/.local/share/gnome-shell/extensions/public-ip-extension@rostegg.github.com 
```
Extension worked after installation but after first reboot crashed and is impossible to turn on again.

```
Error: Tried to construct an object without a GType; are you using GObject.registerClass() when inheriting from a GObject type?

Stack trace:
  PublicIpPrefs@/home/mzylowski/.local/share/gnome-shell/extensions/public-ip-extension@rostegg.github.com/prefs.js:17:3
  buildPrefsWidget@/home/mzylowski/.local/share/gnome-shell/extensions/public-ip-extension@rostegg.github.com/prefs.js:71:15
  _showPrefs@resource:///org/gnome/shell/extensionPrefs/main.js:174:38
  openPrefs@resource:///org/gnome/shell/extensionPrefs/main.js:159:24
  _init/<@resource:///org/gnome/shell/extensionPrefs/main.js:600:62
  main@resource:///org/gnome/shell/extensionPrefs/main.js:762:23
  @<main>:1:48
```

**Comment by rostegg** [comment]
Do you use https://extensions.gnome.org for any another extensions (or earlier installed this extension through it)?

If it works fine, but crashed after reboot, it seems downgrade extension to previous version from site.
Could you compare, please, [this](https://github.com/rostegg/public-ip-gnome-extension/blob/9482f00877b4c14bfa674ffab7ffc456022ff493/prefs.js#L17) line with line at your local file (/home/mzylowski/.local/share/gnome-shell/extensions/public-ip-extension@rostegg.github.com/prefs.js:17)?

I also had such a problem that it tried to automatically download the version from the site. 
If so, then I will create a temporary instance of extension on the site for version >=3.36

**Comment by kiranjisac** [comment]
Hi rostegg , It occured for me also automatically downgraded to previous version from site .please do something about it

**Comment by kiranjisac** [comment]
17th  line of prefs.js  is different

**Comment by kiranjisac** [comment]
Hi I have a doubt will this problem resolve if I change the version in the metadata.json

**Comment by mzylowski** [comment]
> Do you use https://extensions.gnome.org for any another extensions (or earlier installed this extension through it)?

Yeah, I have few extension from gnome.org and yes, earlier I tried to install IP addon from gnome.org

Line 17 from `prefs.js` is `super();`, few lines from this block:
```const DISPLAY_MODES = ['only-flag', 'only-ip', 'ip-and-flag'];

const init = () => {/* Empty */};

class PublicIpPrefs extends Gtk.Grid {

        constructor() {
                super();
                this.margin = 15;
                this.row_spacing = 3;
                this._settings = Convenience.getSettings();

                let label = null;
                let container = null;

                /* Refresh rate */
                container = new Gtk.HBox({spacing: 5});
```
> it seems downgrade extension to previous version from site

Yep, I can confirm that. I fully reproduced this issue by: removing my extension through gnome.org, git clone 3.36 branch, reboot. For some reason my addon is downgraded after reboot.

Thanks,
Michal

**Comment by rostegg** [comment]
So, i decide to [create compatible fix](https://github.com/rostegg/public-ip-gnome-extension/tree/gnome-compatible-version) with earlier versions (<=3.32) in one extension, because manage two version of extension seems not good for me.

I tested it on few versiones (3.30 - 3.36), work ok, but problems with displaying preferences.
As soon, as I complete fixes (1-2 day, now just a little bit busy), I will update it on the site.

**Comment by rostegg** [comment]
First of all, I want to apologize for such a long delay. It so happened that I could not make changes and the promised couple of days turned into a couple of weeks. Fix was tested on versions 3.26 - 3.36 shells, everything worked ok.

Fix already on [review list](https://extensions.gnome.org/review/), usually review takes a couple of days, so as soon as it's reviewed , I'll let you know.

**Comment by sgrzy01** [comment]
> First of all, I want to apologize for such a long delay. It so happened that I could not make changes and the promised couple of days turned into a couple of weeks. Fix was tested on versions 3.26 - 3.36 shells, everything worked ok.
> 
> Fix already on [review list](https://extensions.gnome.org/review/), usually review takes a couple of days, so as soon as it's reviewed , I'll let you know.

Thank you for your work to fix this... its a small but important (imho) extension and i appreciate it!

**Comment by rostegg** [comment]
Ok, extension already was reviewed. I tested it again, but already from the site, everything seems to be fine. If within a week there are no problems, then I will merge fix to the master branch and close the issue.

**Comment by mzylowski** [comment]
Thanks, I can confirm extension installed from gnome.org works well

**Comment by aminvakil** [comment]
> Ok, extension already was reviewed. I tested it again, but already from the site, everything seems to be fine. If within a week there are no problems, then I will merge fix to the master branch and close the issue.

It's been a week from your commit, if you think time is appropriate please merge the fix to the master branch.

**Comment by rostegg** [comment]
General version in master branch. I also left branches for [version <= 3.24](https://github.com/rostegg/public-ip-gnome-extension/tree/origin-version) and for [version 3.36 only](https://github.com/rostegg/public-ip-gnome-extension/tree/gnome-3.36-hotfix).

For a week there were no issues, so that will assume that so far everything is ok.

**Comment by aminvakil** [comment]
Thanks, AUR package updated as well.
