### ISSUE TITLE
Layout improvements

### ISSUE THREAD

**Issue by sojusnik** [rostegg/public-ip-gnome-extension#2]
Thanks for this extension!

On my Gnome 3.30.1 on Ubuntu 18.10 the country flag isn't aligned with the IP adress, as shown [here](https://i.imgur.com/NJ89rDC.png).

Do you though about using other country icons, since the current ones look a little blurry?

BTW, an option to show only the country flag would be great to have!

**Comment by rostegg** [comment]
> Thanks for this extension!
> 
> On my Gnome 3.30.1 on Ubuntu 18.10 the country flag isn't aligned with the IP adress, as shown [here](https://i.imgur.com/NJ89rDC.png).
> 
> Do you though about using other country icons, since the current ones look a little blurry?
> 
> BTW, an option to show only the country flag would be great to have!

Just tested on Gnome 3.30.1, it seems to be working [correctly](https://i.imgur.com/NoNXJvm.png).

From the screenshot, it seems, the panel is at the bottom of the desktop. Do you use any extension for this?

About display only flags and new icons pack, i will add these features, but not in the near future (maybe in a couple of weeks). 

If you want to display only the flag, then I advise you to use [this](https://extensions.gnome.org/extension/1004/public-ip-address/) extension

**Comment by sojusnik** [comment]
> From the screenshot, it seems, the panel is at the bottom of the desktop. Do you use any extension for this?

Yes, I'm using [Dash to Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/).

> Just tested on Gnome 3.30.1, it seems to be working correctly.

Even in your screenshot the IP address is not aligned properly – it's not on the same height as, for example, the time. The same goes for the flag in comparison to other icons on your panel.

> About display only flags and new icons pack, i will add these features, but not in the near future (maybe in a couple of weeks).

Great, thanks!

> If you want to display only the flag, then I advise you to use this extension

This one is outdated and not maintained anymore, as is [this](https://extensions.gnome.org/extension/1190/ip-finder/).

**Comment by rostegg** [comment]
> 
> Even in your screenshot the IP address is not aligned properly – it's not on the same height as, for example, the time. The same goes for the flag in comparison to other icons on your panel.
> 
Okay, now it's seems to look [okay](https://i.imgur.com/tVXn5XC.png), just clone repository to apply fixes.

I'll post it on the GnomeExtensions later, when I add new features, anyway review there takes a very long time.

**Comment by sojusnik** [comment]
Thanks, much better now!

Can't wait to have the new features!
