### ISSUE TITLE
Не меняется флаг при смене ip-адреса

### ISSUE THREAD

**Issue by qwite** [rostegg/public-ip-gnome-extension#3]
Пользуюсь VPN. При смене ip не меняется флаг, скриншоты прилагаю. 

![снимок_3](https://user-images.githubusercontent.com/13612782/55675996-2810a000-58d4-11e9-90d4-c63d08027b69.png)

![снимок_1](https://user-images.githubusercontent.com/13612782/55676006-44acd800-58d4-11e9-8996-0cfa5ce12c3e.png)

http://ip-api.com
![снимок_2](https://user-images.githubusercontent.com/13612782/55675990-0a433b00-58d4-11e9-82c2-c12602d0c3f2.png)

**Comment by rostegg** [comment]
> Пользуюсь VPN. При смене ip не меняется флаг, скриншоты прилагаю.
> 
> ![снимок_3](https://user-images.githubusercontent.com/13612782/55675996-2810a000-58d4-11e9-90d4-c63d08027b69.png)
> 
> ![снимок_1](https://user-images.githubusercontent.com/13612782/55676006-44acd800-58d4-11e9-8996-0cfa5ce12c3e.png)
> 
> http://ip-api.com
> ![снимок_2](https://user-images.githubusercontent.com/13612782/55675990-0a433b00-58d4-11e9-82c2-c12602d0c3f2.png)

Проблема была в иконке Нидерландов, попробуйте заклонить репозиторий или просто поменять иконку на новую, из комита.

**Comment by qwite** [comment]
> Проблема была в иконке Нидерландов, попробуйте заклонить репозиторий или просто поменять иконку на новую, из комита.

Все заработало, спасибо! <3
