### ISSUE TITLE
ip only mode

### ISSUE THREAD

**Issue by ztychr** [rostegg/public-ip-gnome-extension#4]
If you're still maintaining this extension, could you add a third mode with the ip shown, but no flags?

**Comment by rostegg** [comment]
It sounds reasonable, I'll add a feature, but at the moment, I don't have time for this, so the issue will be open for a while

**Comment by rostegg** [comment]
@ztychr Ok, I quickly made feature, everything works, you can update it manually, it will appear on the site as soon as the review is pass

**Comment by ztychr** [comment]
@rostegg Works great. Thank you for your effort.
