### ISSUE TITLE
switching upon reboot

### ISSUE THREAD

**Issue by ztychr** [rostegg/public-ip-gnome-extension#5]
The ip only option changes back to ip + flag in the display after rebooting. This is fixed by changing to another option and then back to ip only. 

While I don't mind changing it back whenever rebooting, I wanted to make you aware of this. Don't waste your time fixing this for me.

Thank you again for your effort.

**Comment by rostegg** [comment]
Just forgot to get default parameters at startup, now everything should work.

**Comment by rostegg** [comment]
@ztychr 
When you checked whether everything works correctly, let me know

**Comment by ztychr** [comment]
Seems to work just fine now. thanks
