### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by aminvakil** [rostegg/public-ip-gnome-extension#8]
Your plugin is great and as a sysadmin I'm always tunneling through different VPNs, changing routings, etc. and your plugin is very useful to me.

So I decided to create an AUR package which installs your plugin from your git and named you as contributor also.

I would be honoured if I could create a pull request and change readme so people can use my aur as well.

**Comment by rostegg** [comment]
Of course, I will look forward for pull request. Thank you for your interest.
